# Generated by Django 3.2.23 on 2024-03-01 09:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_csvimport'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='csv_file',
            field=models.FileField(blank=True, null=True, upload_to='csv_files/'),
        ),
        migrations.AddField(
            model_name='post',
            name='uploaded_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
